version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fastify
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: always
    networks:
      - app
  postgres:
    image: postgres:16-alpine
    container_name: postgres
      #    volumes:
      #- ./data:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    networks:
      - app
    env_file:
      - ./server/postgres.env

networks:
  app:
    name: app
    driver: bridge
